DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS(
    REFERENCE VARCHAR(16) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    BRAND VARCHAR(50) NOT NULL,
    PACKING VARCHAR(50) NOT NULL,
    QUANTITY VARCHAR(10) NOT NULL,
    LABELS VARCHAR(255),
    ORIGIN VARCHAR(50) NOT NULL,
    NUTRISCORE CHAR NOT NULL,
    NOVASCORE INT,
    ECOSCORE CHAR NOT NULL,
    EXPLANATION VARCHAR(255) NOT NULL,
    PRIMARY KEY (REFERENCE)
);

INSERT INTO PRODUCTS VALUES ('0001', 'Coca-Cola 33ml 6-pack', 'Drink', 'Coca-Cola', 'plastic', '6 cans', 'Good but bad', 'USA', 'D', '4', 'E', 'ta mere le triceratops tetraplegique');