DROP TABLE IF EXISTS TEXT;

CREATE TABLE TEXT(
    ID VARCHAR(16) NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    TEXT_TYPE VARCHAR(16) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO TEXT VALUES ('PAPA', 'PAPA BAISE TES MORTS', 'BAD');